sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username:
    password:
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    #oss的ID
    access-key-id:
    #密钥
    access-key-secret:
    bucket-name:
#TODO 改为自己的id->key
  redis:
    host: localhost
    port: 6379
    #密码
    password:
    database: 0
  wechat:
    appid:
    secret: