sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ysp666
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tSeESmsC2d3FMtNVHAY
    access-key-secret: juFkH7vGx55WFWTHnXo8MjqSSEKxW6
    bucket-name: hmleadnews-ysp
#TODO 改为自己的id->key
  redis:
    host: localhost
    port: 6379
    password: ysp666
    database: 0
  wechat:
    appid: wx33d18957848c036c
    secret: 4b8c06c585494e7815561f9bd99f5392